// Finds the mods in mods/<folder>/index.tsx and writes mods/index.generated.ts, the one file the app and the
// render import them from (both bundlers need static imports). Also creates a new mod from the template.
import fs from 'node:fs';
import path from 'node:path';

export const MODS_DIR = path.resolve(import.meta.dirname, '..', 'mods');
export const INDEX_FILE = 'index.generated.ts';
const ENTRIES = ['index.tsx', 'index.ts'];

/** Folder name → a JS identifier for its import (m0, m1…), in alphabetical order so the output is stable. */
export const indexSource = (mods: { folder: string; entry: string }[]): string => {
  const lines = [
    '// Generated by scripts/mods.ts from the folders in mods/. Do not edit: it is rewritten when mods change.',
    "import type { ModModule } from '../src/lib/mods.ts';",
    ...mods.map((m, i) => `import * as m${i} from './${m.folder}/${m.entry}';`),
    '',
    `export const modules: ModModule[] = [${mods.map((m, i) => `\n  { folder: ${JSON.stringify(m.folder)}, module: m${i} },`).join('')}${mods.length ? '\n' : ''}];`,
    '',
  ];
  return lines.join('\n');
};

/** Each folder in `dir` with an index.tsx (or index.ts). Folders starting with "." or "_" are skipped (drafts). */
export const findMods = (dir: string): { folder: string; entry: string }[] => {
  if (!fs.existsSync(dir)) return [];
  return fs
    .readdirSync(dir, { withFileTypes: true })
    .filter((d) => d.isDirectory() && !d.name.startsWith('.') && !d.name.startsWith('_'))
    .map((d) => ({ folder: d.name, entry: ENTRIES.find((e) => fs.existsSync(path.join(dir, d.name, e))) }))
    .filter((m): m is { folder: string; entry: string } => !!m.entry)
    .sort((a, b) => a.folder.localeCompare(b.folder));
};

/** Rewrites the index only if it changed (so the dev server doesn't reload for nothing). True if it wrote. */
export const writeModsIndex = (dir = MODS_DIR): boolean => {
  fs.mkdirSync(dir, { recursive: true });
  const file = path.join(dir, INDEX_FILE);
  const source = indexSource(findMods(dir));
  if (fs.existsSync(file) && fs.readFileSync(file, 'utf8') === source) return false;
  fs.writeFileSync(file, source);
  return true;
};

/** "My cool effect" → "my-cool-effect". */
export const toModId = (name: string): string =>
  name
    .normalize('NFD')
    .replace(/[̀-ͯ]/g, '')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');

const toTitle = (id: string) => id.replace(/-/g, ' ').replace(/^./, (c) => c.toUpperCase());
const toCamel = (id: string) => id.replace(/-([a-z0-9])/g, (_, c: string) => c.toUpperCase());

/** Code of a new mod: a working effect to start from (a word that pops in over your video). */
export const modTemplate = (id: string): string => `// ${toTitle(id)}: a mod for Visual Hooks. Docs: docs/mods.md
// Everything you need comes from src/sdk.ts. Animate with \`t\` (seconds), never with the real clock or Math.random():
// that keeps the preview and the export identical, frame by frame.
import React from 'react';
import { AbsoluteFill, useCurrentFrame } from 'remotion';
import {
  colorOf,
  easeOutBack,
  fonts,
  lerp,
  MediaBackdrop,
  progress,
  timeOf,
  type BaseProps,
  type EffectDef,
  type PaletteColor,
} from '../../src/sdk.ts';

type Props = { text: string; color: PaletteColor; dim: number };

const Effect: React.FC<Props & BaseProps> = (p) => {
  const t = timeOf(useCurrentFrame(), p.fps, p.speed);
  const pop = easeOutBack(progress(t, 0.15, 0.45));
  return (
    <AbsoluteFill>
      <MediaBackdrop media={p.media} fit="cover" dim={p.dim * progress(t, 0, 0.3)} />
      <AbsoluteFill style={{ justifyContent: 'center', alignItems: 'center' }}>
        <div
          style={{
            transform: \`scale(\${lerp(0.2, 1, pop)}) rotate(\${lerp(-12, -3, pop)}deg)\`,
            opacity: progress(t, 0.15, 0.1),
            padding: '24px 48px',
            borderRadius: 28,
            background: colorOf(p.color),
            color: '#0a0b0d',
            fontFamily: fonts.sans,
            fontWeight: 800,
            fontSize: 120,
          }}
        >
          {p.text}
        </div>
      </AbsoluteFill>
    </AbsoluteFill>
  );
};

export const ${toCamel(id)}: EffectDef<Props> = {
  id: '${id}',
  name: { en: '${toTitle(id)}', es: '${toTitle(id)}' },
  group: 'hook',
  description: { en: 'Describe your effect in one line.', es: 'Describe tu efecto en una línea.' },
  author: '@your.handle',
  usesMedia: true,
  defaultDurationSec: 2,
  defaults: { text: 'Wow', color: 'mint', dim: 0.5 },
  localized: { es: { text: 'Guau' } },
  params: [
    { key: 'text', label: { en: 'Text', es: 'Texto' }, type: 'text' },
    { key: 'color', label: { en: 'Color', es: 'Color' }, type: 'color' },
    { key: 'dim', label: { en: 'Darken your video', es: 'Oscurecer tu video' }, type: 'number', min: 0, max: 1, step: 0.05 },
  ],
  component: Effect,
};

export default ${toCamel(id)};
`;

/** Creates mods/<id>/index.tsx from the template. Returns its path; fails if the folder already exists. */
export const scaffoldMod = (name: string, dir = MODS_DIR): string => {
  const id = toModId(name);
  if (!id) throw new Error('Give the mod a name, e.g.: pnpm new-mod "sticker slap"');
  const folder = path.join(dir, id);
  if (fs.existsSync(folder)) throw new Error(`mods/${id} already exists`);
  fs.mkdirSync(folder, { recursive: true });
  const file = path.join(folder, 'index.tsx');
  fs.writeFileSync(file, modTemplate(id));
  writeModsIndex(dir);
  return file;
};

/** Keeps the index up to date while the app runs: adding or removing a mod folder shows up without a restart. */
export const watchMods = (onChange: () => void, dir = MODS_DIR) => {
  fs.mkdirSync(dir, { recursive: true });
  let timer: NodeJS.Timeout | null = null;
  return fs.watch(dir, { recursive: true }, (_event, file) => {
    if (file && path.basename(String(file)) === INDEX_FILE) return;
    if (timer) clearTimeout(timer);
    timer = setTimeout(() => writeModsIndex(dir) && onChange(), 150);
  });
};
